name: Lighthouse Audit on Vercel

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel Preview
        uses: dolevf/wait-for-vercel@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.VERCEL_TEAM_ID }}
          max_timeout: 300

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse CLI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI on deployed site
        run: lhci autorun --collect.url=${{ steps.vercel.outputs.url }}

